export type Category = {
  id: string
  name: string
}

export type FoodItem = {
  id: string
  name: string
  price: number // integer TWD, e.g. 290 = NT$290
  categoryId: string
  imageUrl: string
}

// Snapshot chain: FoodItem --[add to cart]--> CartItem --[submit order]--> OrderItem
// Each step copies name/price/imageUrl so historical records never break if the menu changes.

export type CartItem = {
  id: string // cart item's own uuid
  foodItemId: string // FK to FoodItem.id
  name: string // snapshotted from FoodItem at add-to-cart time
  price: number // snapshotted from FoodItem at add-to-cart time, integer TWD
  imageUrl: string // snapshotted from FoodItem at add-to-cart time
  quantity: number
}

export type OrderItem = {
  foodItemId: string // FK to FoodItem.id
  name: string // snapshotted from CartItem at order-submit time
  price: number // snapshotted from CartItem at order-submit time, integer TWD
  imageUrl: string // snapshotted from CartItem at order-submit time
  quantity: number
}

export type Order = {
  id: string // uuid generated by server
  items: OrderItem[]
  total: number // integer TWD, calculated by server
  submittedAt: string // generated by server
}
